name: cliftontolboe
favicon: null
layout_spectrum: 1
typography_spectrum: 0.858754
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#788187'
    - '#4B545B'
    - '#D1BB9A'
    - '#F3F3DE'
    - '#38B5B2'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
